# Generated by Django 3.1 on 2020-09-02 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoty',
            new_name='category',
        ),
    ]
